# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

env:
  - DEPLOY_PYPI="false"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pypi
    user: adafruit-travis
    password:
      secure: "uSEQHUsvjBuLSevEjGO0Su2mkxCw9HupzXkT4zEfyHSnIcegOMiZh+rAVWO9GSV+mRA3GmDxrb61Y8V6xHX8kc4oOoym6Zt3q/2WGUolHHJ8s8FdzjA6z6nVU2NPsFXda+NsUBz5X5wEpblZ82XF7agA4BSxy//CEZ4jhxlOHpaZfGO2ZeywDAfN4bPYB7T0JxCZ9qkLzS7DqB6PwFy2wE4b5jLIR1fi+Cengn12KBa1pASuRv0rrrBgTdhQ5D/acm3T57ZBLKCjE1S05kqGVjpkwWWjh8/znCeiYEwqIu8bkqJ6goz3pKkWzU8rKZTooUg/OFZ63TAMtpxRPdWgs560HccdI4zoSLTovnmrvUDk7Vkmc8QNUkYWSyRyWYJpO5je/LpsIUajACBjMp6yQ+iwbED54Uq4+uYVA2z+bn27EEr668+X39Lz1q/TJTIkgaA1Qt+IWYDmaDEY7hFZAOAfDp8ew45WZ3JQa5TAwgCIAxMT3JR87eyj4QitYFNQrlX0QMMLNhqZaPY+pNbRvsXO+zyevF43oDqtOh/VB+Dttaw1PFYQnmIbgDKQCx7Lc5Nbzta5TqOR7r9y2lyxy4W4P8Mp4Z2+2f8mBjZmzhgrP87ehdsFPEDwoPhbnoJQI19nW9b9l1YYoS4AZU25imrclAGOtG8f4d66lP/XlOY="
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint electronutlabs_ltr329als01.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix electronutlabs-circuitpython-ltr329als01 --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
